server:
  port: 0
spring:
  application:
    name: account
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18079/realms/master
  profiles:
    active: kc

#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: "123"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

