server:
  port: 0
spring:
  application:
    name: account
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8079
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:h2_account
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
