###Config local ----------
server:
  port: 0
spring:
  application:
    name: bank
  profiles:
    active: rabbit
  cloud:
## Rabbit MQ
    function:
      definition: inputFrontToBank
    stream:
      bindings:
        inputFrontToBank-in-0:
          destination: bank-destination

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8079
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:h2_bank
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka