
version: "3"
services:
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
    ports:
      - '18079:8080'
    command:
      - start-dev
#      - --http-port=8180
