###Config local ----------
server:
  port: 0
spring:
  application:
    name: shop
  profiles:
    active: rabbit
  cloud:
## Spring Cloud Circuit Breaker
    openfeign:
      circuitbreaker:
        enabled: true
## Rabbit MQ
    function:
      definition: newMessageShop
    stream:
      bindings:
        newMessageShop-out-0:
          destination: bank-destination

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:h2
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


#  datasource:
#    url: jdbc:postgresql://localhost:5432/microshop_shop
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: 123
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




