server:
  port: 8080
#  servlet:
#    session:
#      cookie:
#        http-only: off

### local variable
microshop:
  service:
    shop:
      uri: http://localhost:8765
      registration-id: keycloak

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18079/realms/master
#            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: my-front-app
            client-secret: q9NqxhVTeFlxcuKuOSiNUYEmj16AJ4cC
            scope:
              - openid
              - microprofile-jwt
              - view_catalog
#      resourceserver:
#        jwt:
#          issuer-uri: http://127.0.0.1:18079/realms/master


### setting for admin keycloak
  #        provider:
  #          keycloak:
  #            #            issuer-uri: http://localhost:18079/realms/shop-realm
  #            issuer-uri: http://localhost:18079/realms/master
  #            user-name-attribute: preferred_username
  #        registration:
  #          my-front-app-client-credentials:
  #            provider: keycloak
  #            authorization-grant-type: client_credentials
  #            client-id: my-front-app
  #            client-secret: q9NqxhVTeFlxcuKuOSiNUYEmj16AJ4cC
  #            scope:
  #              - openid
  #              - microprofile-jwt
  #          my-front-app-authorization-code:
  #            provider: keycloak
  #            authorization-grant-type: client_credentials
  #            client-id: my-front-app
  #            client-secret: q9NqxhVTeFlxcuKuOSiNUYEmj16AJ4cC
  #            scope:
  #              - openid
  #              - microprofile-jwt

  #spring:
  jpa:
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


