#server:
#  port: 9000
spring:
#  application:
#    name: entity
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:h2_entity
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ""
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect



#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:h2_entity
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ""
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
