###Config local ----------
server:
  port: 0
spring:
  application:
    name: storage
  profiles:
    active: rabbit

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:h2_storage
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

